### ISSUE TITLE
The tabs bounce up and down when changing font size

### ISSUE THREAD

**Issue by rwols** [SublimeText/Theme-DAneo#10]
I don't think this happened in older builds. Here's a gif of what happens:

![output](https://user-images.githubusercontent.com/2431823/96635014-9c2a6180-131b-11eb-8736-e10599182a36.gif)

I'm pressing <kbd>cmd</kbd><kbd>+</kbd> (increase font size) here a few times, then decrease it again. The tabs move up and down when doing so. After that I switch to the Default theme. The Default theme doesn't have this behavior for some reason.

**Environment**
Theme: DAneo minimal
Color scheme: Mariana
ST build 4089
macOS 10.15.6

**Comment by deathaxe** [comment]
I don't see how this maight be caused by the theme.

Font size changes should only effect the editor control.

The only change in 0.4.6 with regards to MacOS title bar control is the color being tweaked to match the sidebar.

All theme controls use a static size. ST might adjust widget sizes as they use the editor's font size. But those are text input controls of command palette, overlay control and find and replace panel.

Must be a core issue.

Anyway, I wouldn't be able to debug it as I never saw and propably never will have a Mac in reachable distance.
