### ISSUE TITLE
Too small padding on the right side of the quick panel

### ISSUE THREAD

**Issue by rchl** [SublimeText/Theme-DAneo#7]
I think this popup could have a bit more padding on the right. In the screenshot you can see that the overlay scrollbar overlays the text a bit which doesn't look great but even without the scrollbar the padding feels a bit too small and uneven when comparing to the left side.

![Screenshot 2020-09-04 at 09 33 59](https://user-images.githubusercontent.com/153197/92212167-d89c1e00-ee91-11ea-9547-60c6443758c5.png)

**Comment by deathaxe** [comment]
Overlay scrollbars may overlap with scroll area content by design. ST doesn't provide a dedicated rendering area for the overlay scrollbar. That's why the scroll track and puck are rendered semi-transparent.

That said the padding may need some tweaks in general to better match normal and kind info containing quick panels.
