### ISSUE TITLE
Panels Render Incorrectly

### ISSUE THREAD

**Issue by byronvanstien** [SublimeText/Theme-DAneo#8]
![image](https://user-images.githubusercontent.com/19594846/94393192-4f0b0380-0152-11eb-9c80-c504c9355c1a.png)

Build 4087

**Comment by deathaxe** [comment]
Looks like textures are missing. Maybe the sublime-package got corrupted? I am running ST 4087 on Windows as well without issues. 

Otherwise console might print out error messages in case of parse errors or missing files. Maybe an overriding theme file exists which causes the theme definition to break?

**Comment by byronvanstien** [comment]
Hi

Thanks for pointing me in the right direction; used GitHub Desktop to clone it as I didn't have raw Git installed on this machine. As there's no spaces between `Theme-DAneo` in the repo title it also clones that way. The package itself is looking for  `Theme - DAneo`. As a result it was trying to decode files that didn't exist.

Hope this helps anyone else that finds themselves in that particular pickle :)
